# Generated by Django 2.0.6 on 2018-07-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='news_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
